.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UAU" "1" "April 2017" "" ""
.
.SH "NAME"
\fBuAu\fR \- unattended Arch upgrade is a little helper to damage your system by installing Arch upgrades non\-interactively
.
.SH "SYNOPSIS"
\fBuau\fR (will be executed by systemd)
.
.br
\fBuau\-news\fR (will be executed by \fBuau\fR)
.
.SH "DESCRIPTION"
Unattended upgrades are completely against the Arch philosophy!
.
.P
So \fBNEVER ever\fR set the \fIAUTOUPGRADE\fR of uAu ;)
.
.P
\fBThe usual Arch upgrade flow\fR
.
.P
BEFORE starting any upgrade
.
.IP "" 4
.
.nf

1) Read the Arch news site
2) If you use packages from the AUR it is recommended to check the latest comments there
3) Take your time for doing the upgrade
.
.fi
.
.IP "" 0
.
.P
DOING the upgrade
.
.IP "" 4
.
.nf

4) Always sync the databases before doing anything else
5) Partial Upgrades are totally unsupported! So never ever use "IgnorePkg" \-\-ignore or \-\-ignoregroup
6) Sit down, answer questions, make the upgrade interactively
.
.fi
.
.IP "" 0
.
.P
AFTER the upgrade
.
.IP "" 4
.
.nf

7) Check systemd failure states
8) Check journal for high prio errors
.
.fi
.
.IP "" 0
.
.P
\fBThe uAu flow (default)\fR
.
.P
uAu will by default do for you:
.
.IP "" 4
.
.nf

steps 1,2 and 4 and send this by Email so you stay informed in order to do the other steps
.
.fi
.
.IP "" 0
.
.P
\fBThe uAu flow (advanced)\fR
.
.P
uAu CAN do for you (if you change the default setting):
.
.IP "" 4
.
.nf

steps 1\-8 and send you the results by Email
(means a fully unattended upgrade with all the above)
.
.fi
.
.IP "" 0
.
.SH "FILES"
The following files should be reviewed and maybe adjusted for your needs:
.
.P
\fI/etc/unattended\-arch\-upgrade\.conf\fR
.
.IP "" 4
.
.nf

             The main configuration file
.
.fi
.
.IP "" 0
.
.P
\fI/etc/unattended\-arch\-upgrade\.ignore\fR
.
.IP "" 4
.
.nf

             uAu package ignores for an unattended upgrade
.
.fi
.
.IP "" 0
.
.P
\fI/etc/cron\.d/archnews\fR
.
.IP "" 4
.
.nf

             Time setting for the uAu info mail
.
.fi
.
.IP "" 0
.
.P
\fI/unattended\-arch\-upgrade\.timer\fR
.
.IP "" 4
.
.nf

             Timer for starting uAu
.
.fi
.
.IP "" 0
.
.SH "AUTHOR"
steadfasterX \fIsteadfastX@boun\.cr\fR
.
.SH "SEE ALSO"
\fBman 5 uau\fR
.
.P
uAu on github \fIhttps://github\.com/steadfasterX/arch_unattended\-upgrade\fR
