.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "UAU" "1" "April 2017" "" ""
.
.SH "NAME"
\fBuAu\fR \- unattended Arch upgrade is a little helper to damage your system by installing Arch upgrades non\-interactively
.
.SH "DESCRIPTION"
Global(!) description for the main parts of uAu\.
.
.SH "unattended\-arch\-upgrade\.service"
The service responsible to DAMAGE your system\. It is controlled by the uAu timer (unattended\-arch\-upgrade\.timer)
.
.SH "unattended\-arch\-upgrade\.timer"
This timer controls unattended\-arch\-upgrade\.service\.
.
.P
The OnCalendar function let you choose systemd time \fIhttp://man7\.org/linux/man\-pages/man7/systemd\.time\.7\.html#CALENDAR_EVENTS\fR
.
.P
Persistent=false is set by default which means uAu will NOT do an immediate action when the time passed by and the PC was offline\.
.
.SH "unattended\-arch\-upgrade\.conf"
The main configuration file for uAu\. This has to be adjusted to your needs\. Especially when you want to activate the damage eehm\.\. upgrade feature\.
.
.SH "unattended\-arch\-upgrade\.ignore"
The option IgnorePkg EXTENDS the pacman IgnorePkg\. This way you can have different ignores when doing a regular upgrade and an unattended\.
.
.SH "AUTHOR"
steadfasterX \fIsteadfastX@boun\.cr\fR
.
.SH "SEE ALSO"
uAu on github \fIhttps://github\.com/steadfasterX/arch_unattended\-upgrade\fR
